version: "2"
services:
  scheduled_checkin:
    image: scheduled-checkin-service
    restart: always
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
